---
collections:
  - name: https://github.com/ansible-collections/community.docker.git
    type: git
    # Immutable commit behind the community.docker 5.2.2 release tag.
    version: 44812d46a5072eec78175a41a1100ee77218c8a2
