accept = [200, 204, 206, 429]
exclude = [
  '^https://github\.com/lowerduckpond-net/lowerduckpond\.net/security/advisories/new$',
]
exclude_all_private = true
max_concurrency = 8
max_retries = 3
no_progress = true
timeout = 20
