---
all:
  children:
    hosting_nodes:
      hosts:
        lowerduckpond_production_01:
          ansible_host: >-
            {{ lookup('ansible.builtin.env', 'PRODUCTION_ORIGIN_IPV4') |
               mandatory }}
          ansible_user: ldp-admin
          ansible_ssh_common_args: -o HostKeyAlias=lowerduckpond.net
          caddy_domain: lowerduckpond.net
          backup_node_name: lowerduckpond-production-01
