---
all:
  children:
    hosting_nodes:
      hosts:
        lowerduckpond_production_01:
          ansible_host: lowerduckpond.net
          ansible_user: ldp-admin
          caddy_domain: lowerduckpond.net
          backup_node_name: lowerduckpond-production-01
