"""Strict, transport-independent static-publication contracts."""

from lowerduckpond_static_contracts.canonical import (
    MAX_CANONICAL_BYTES,
    MAX_RAW_REQUEST_BYTES,
    canonical_json_bytes,
    decode_json_object,
)
from lowerduckpond_static_contracts.digest import (
    Digest,
    archive_record_digest,
    audit_entry_digest,
    deployment_record_digest,
    manifest_digest,
    platform_state_digest,
    request_digest,
    result_digest,
)
from lowerduckpond_static_contracts.errors import ContractError, ErrorCode, ResultErrorCode
from lowerduckpond_static_contracts.identifiers import (
    RESERVED_SLUGS,
    validate_slug,
    validate_uuid7,
)
from lowerduckpond_static_contracts.lifecycle import (
    LIFECYCLE_MATRIX,
    TRANSACTION_PHASE_TRANSITIONS,
    LifecycleState,
    Operation,
    TransactionPhase,
)
from lowerduckpond_static_contracts.operator_protocol import (
    HEADER_SIZE,
    MAGIC,
    MAX_DEPLOY_ARTIFACT_BYTES,
    MAX_EXPORT_BYTES,
    MAX_IMPORT_ARTIFACT_BYTES,
    MAX_RESPONSE_BYTES,
    VERSION,
    FrameHeader,
    FrameKind,
    ProtocolError,
    decode_header,
    encode_header,
)
from lowerduckpond_static_contracts.schema import (
    ContractKind,
    decode_contract,
    decode_request,
    decode_result,
    materialize_create_request,
    materialize_platform_namespace,
    validate_contract,
)
from lowerduckpond_static_contracts.values import (
    ValidatedCreateRequest,
    ValidatedPlatformNamespace,
)

__all__ = [
    "HEADER_SIZE",
    "LIFECYCLE_MATRIX",
    "MAGIC",
    "MAX_CANONICAL_BYTES",
    "MAX_DEPLOY_ARTIFACT_BYTES",
    "MAX_EXPORT_BYTES",
    "MAX_IMPORT_ARTIFACT_BYTES",
    "MAX_RAW_REQUEST_BYTES",
    "MAX_RESPONSE_BYTES",
    "RESERVED_SLUGS",
    "TRANSACTION_PHASE_TRANSITIONS",
    "VERSION",
    "ContractError",
    "ContractKind",
    "Digest",
    "ErrorCode",
    "FrameHeader",
    "FrameKind",
    "LifecycleState",
    "Operation",
    "ProtocolError",
    "ResultErrorCode",
    "TransactionPhase",
    "ValidatedCreateRequest",
    "ValidatedPlatformNamespace",
    "archive_record_digest",
    "audit_entry_digest",
    "canonical_json_bytes",
    "decode_contract",
    "decode_header",
    "decode_json_object",
    "decode_request",
    "decode_result",
    "deployment_record_digest",
    "encode_header",
    "manifest_digest",
    "materialize_create_request",
    "materialize_platform_namespace",
    "platform_state_digest",
    "request_digest",
    "result_digest",
    "validate_contract",
    "validate_slug",
    "validate_uuid7",
]
