FROM {{ item.image }}

ENV container=docker
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        iproute2 \
        openssh-client \
        python3 \
        sudo \
        systemd \
        systemd-sysv \
    && apt-get clean \
    && find /var/lib/apt/lists -mindepth 1 -delete

RUN systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount \
    systemd-remount-fs.service

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
