FROM python@sha256:be8ccd085666c34273c9dc5607c9842f8b2e3116128aae45148ce164c07ce09d

ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH=/workspace/host-agent

WORKDIR /workspace
COPY tool /workspace/tool
COPY artifact/site-packages /workspace/host-agent
COPY test_archive_remote_minio.py /workspace/test_archive_remote_minio.py
RUN python -m pip install \
    botocore==1.43.78 \
    pytest==9.0.2 \
    /workspace/tool

CMD ["python", "-m", "pytest", "-m", "minio", "/workspace/tool/tests/test_minio.py", "/workspace/test_archive_remote_minio.py"]
