---
- name: Reload rootless Podman services
  ansible.builtin.systemd_service:
    scope: user
    daemon_reload: true
  become_user: "{{ podman_service_user }}"
  become: true
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ podman_service_uid }}/bus"
    HOME: "{{ podman_service_home }}"
    XDG_RUNTIME_DIR: "/run/user/{{ podman_service_uid }}"
